#!/bin/bash

temp=$(/opt/vc/bin/vcgencmd measure_temp|cut -d "=" -f 2| cut -d "'" -f 1)

output="Temperature: $temp"

if ! [[ "$temp" =~ ^([0-9]+|[0-9]*\.[1-9][0-9]*)$ ]]
then
        echo "UNKNOWN- $output"
	exit 3
elif (( $(echo "$temp < 50" |bc -l) ))
then
	echo "OK- $output"
	exit 0
elif (( $(echo "$temp < 60" |bc -l) ))
then
	echo "WARNING- $output"
	exit 1
elif (( $(echo "$temp > 60" |bc -l) ))
then
	echo "CRITICAL- $output"
	exit 2
else
	echo "UNKNOWN- $output"
	exit 3
fi
